# Generated by Django 5.0.6 on 2024-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_customuser_confirmed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedapp',
            name='app',
            field=models.FileField(upload_to='apps/'),
        ),
        migrations.AlterField(
            model_name='uploadedapp',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploadedapp',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploadedapp',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
