# Generated by Django 5.0.6 on 2024-07-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_alter_uploadedapp_app_alter_uploadedapp_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedapp',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='uploadedapp',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='uploadedapp',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
