# Generated by Django 5.0.6 on 2024-07-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_uploadedapp_description_uploadedapp_image4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('app_name', models.CharField(max_length=100)),
            ],
        ),
    ]
